-- 一段読書システム ジャンルタグ初期データ投入SQL

-- ジャンルタグの初期データ
INSERT INTO genre_tags (name, description, category, display_order, is_active) VALUES
-- ジャンルタグ
('自己啓発', '成功法則、習慣形成、モチベーション', 'genre', 1, true),
('ビジネス', '経営、マーケティング、投資', 'genre', 2, true),
('心理学', '人間心理、コミュニケーション', 'genre', 3, true),
('哲学', '人生論、価値観、思考法', 'genre', 4, true),
('歴史', '世界史、日本史、社会問題', 'genre', 5, true),
('科学', 'IT、テクノロジー、自然科学', 'genre', 6, true),
('健康', '健康法、料理、ライフハック', 'genre', 7, true),
('小説', '純文学、エンタメ小説', 'genre', 8, true),

-- 目的関連タグ
('教養', '一般教養・知識向上', 'knowledge', 10, true),
('社会問題', '現代社会の課題', 'knowledge', 11, true),
('人類学', '人類の歴史と文化', 'knowledge', 12, true),
('スキルアップ', '技術・能力向上', 'skill', 20, true),
('プレゼンテーション', '発表・説明技術', 'skill', 21, true),
('データ分析', 'データ処理・分析', 'skill', 22, true),
('統計', '統計学・確率', 'skill', 23, true),
('成功法則', '成功のためのノウハウ', 'growth', 30, true),
('習慣', '習慣形成・改善', 'growth', 31, true),
('人生論', '人生観・価値観', 'growth', 32, true),
('アドラー心理学', 'アドラー心理学関連', 'growth', 33, true),
('マンガ', 'マンガ・コミック', 'relaxation', 40, true),
('エンタメ', 'エンターテイメント', 'relaxation', 41, true),
('文学', '純文学・古典', 'relaxation', 42, true),
('コミュニケーション', '人間関係・対話技術', 'common', 50, true),
('入門書', '初心者向け・わかりやすい', 'common', 51, true),
('思考法', '思考方法・論理', 'common', 52, true),
('未来', '将来・未来予測', 'common', 53, true),
('ライフスタイル', '生活・ライフスタイル', 'common', 54, true),
('成長', '個人的成長・発達', 'common', 55, true),

-- 追加タグ（マイグレーションファイルから）
('起業家', '起業・スタートアップ', 'business', 60, true),
('リクルート', 'リクルート関連', 'business', 61, true),
('江副浩正', 'リクルート創業者', 'person', 62, true),
('藤田晋', 'サイバーエージェント創業者', 'person', 63, true),
('堀江貴文', 'ライブドア創業者', 'person', 64, true),
('宇野康秀', 'GMO創業者', 'person', 65, true),
('三木谷浩史', '楽天創業者', 'person', 66, true),
('山田進太郎', 'メルカリ創業者', 'person', 67, true),
('熊谷正寿', 'GMO創業者', 'person', 68, true),
('柳井正', 'ファーストリテイリング創業者', 'person', 69, true),
('見城徹', '幻冬舎社長', 'person', 70, true),
('草彅剛', 'SMAPメンバー', 'person', 71, true),
('アイドル', 'アイドル関連', 'entertainment', 72, true),
('SF', 'サイエンスフィクション', 'fiction', 73, true),
('数学', '数学・数理', 'science', 74, true),
('暗号', '暗号・セキュリティ', 'technology', 75, true),
('ピーターティール', 'PayPal創業者', 'person', 76, true),
('事業開発', '事業開発・戦略', 'business', 77, true),
('ファッション', 'ファッション・アパレル', 'lifestyle', 78, true),
('ヴィンテージ', 'ヴィンテージ・レトロ', 'lifestyle', 79, true),
('労働', '労働・雇用', 'social', 80, true),
('子育て', '子育て・教育', 'lifestyle', 81, true),
('経営', '経営・マネジメント', 'business', 82, true),
('映画', '映画・映像', 'entertainment', 83, true),
('リーダーシップ', 'リーダーシップ', 'business', 84, true),
('マネージャー', 'マネージャー・管理職', 'business', 85, true),
('経済', '経済・金融', 'social', 86, true),
('SDGs', 'SDGs・サステナビリティ', 'social', 87, true),
('投資', '投資・資産運用', 'finance', 88, true),
('問題解決', '問題解決・課題解決', 'skill', 89, true),
('デザイン', 'デザイン・クリエイティブ', 'creative', 90, true),
('建築', '建築・都市計画', 'creative', 91, true),
('エンジニアリング', 'エンジニアリング・技術', 'technology', 92, true),
('物理', '物理学・自然科学', 'science', 93, true),
('リスキリング', 'リスキリング・再教育', 'skill', 94, true),
('食事', '食事・栄養', 'lifestyle', 95, true),
('組織', '組織・チーム', 'business', 96, true),
('チーム', 'チーム・グループ', 'business', 97, true),
('ノーベル賞受賞者', 'ノーベル賞受賞者', 'person', 98, true),
('政治', '政治・政策', 'social', 99, true),
('洋書', '洋書・翻訳書', 'book_type', 100, true),
('プロダクト開発', 'プロダクト開発', 'technology', 101, true),
('プロセス', 'プロセス・工程', 'business', 102, true),
('計画', '計画・戦略', 'business', 103, true),
('本屋大賞', '本屋大賞受賞作', 'award', 104, true),
('Apple', 'Apple関連', 'company', 105, true),
('ビズリーチ', 'ビズリーチ関連', 'company', 106, true),
('蛯谷 敏', 'ビズリーチ創業者', 'person', 107, true),
('LINEヤフー', 'LINEヤフー関連', 'company', 108, true);
